USE walmart;
SELECT * FROM walmart_table;

DESCRIBE walmart_table;

SELECT COUNT(*) AS total_rows
FROM walmart_table;

SELECT *
FROM walmart_table 
LIMIT 5;

SELECT
  SUM(invoice_id IS NULL) AS null_invoice_id,
  SUM(Branch IS NULL) AS null_branch,
  SUM(City IS NULL) AS null_city,
  SUM(category IS NULL) AS null_category,
  SUM(unit_price IS NULL) AS null_unit_price,
  SUM(quantity IS NULL) AS null_quantity,
  SUM(date IS NULL) AS null_date,
  SUM(time IS NULL) AS null_time,
  SUM(payment_method IS NULL) AS null_payment_method,
  SUM(rating IS NULL) AS null_rating,
  SUM(profit_margin IS NULL) AS null_profit_margin,
  SUM(total IS NULL) AS null_total
FROM walmart_table;

SELECT invoice_id, COUNT(*) AS cnt
FROM walmart_table
GROUP BY invoice_id
HAVING COUNT(*) > 1
ORDER BY cnt DESC;


-- Show only invoice_id, Branch, City

SELECT invoice_id, Branch, City
FROM walmart_table
LIMIT 20;


-- Show unique branches

SELECT DISTINCT Branch
FROM walmart_table;

-- Show unique categories
SELECT DISTINCT category
FROM walmart_table;


-- Top 10 highest total bills
SELECT invoice_id, Branch, City, category, total
FROM walmart_table
ORDER BY total DESC
LIMIT 10;

-- Top 10 largest quantity purchases
SELECT invoice_id, category, quantity, total
FROM walmart_table
ORDER BY quantity DESC
LIMIT 10;


-- Find all payments done by “Cash”
SELECT *
FROM walmart_table
WHERE payment_method = 'Cash'
LIMIT 20;

-- Find all invoices from Branch = 'A'

SELECT *
FROM walmart_table
WHERE Branch = 'A'
LIMIT 20;

-- Bills between 500 and 1000
SELECT invoice_id, total
FROM walmart_table
WHERE total BETWEEN 500 AND 1000
ORDER BY total;

-- Category contains “Food” (LIKE)
SELECT DISTINCT category
FROM walmart_table
WHERE category LIKE '%Food%';


-- Sort by rating (best customer experience)
SELECT invoice_id, Branch, City, category, rating
FROM walmart_table
ORDER BY rating DESC
LIMIT 20;


-- How many transactions happened in each city?
SELECT City, COUNT(*) AS total_transactions
FROM walmart_table
GROUP BY City
ORDER BY total_transactions DESC;

-- Total revenue generated by each branch
SELECT Branch, SUM(total) AS total_revenue
FROM walmart_table
GROUP BY Branch
ORDER BY total_revenue DESC;

-- Average rating per branch
SELECT Branch, ROUND(AVG(rating),2) AS avg_rating
FROM walmart_table
GROUP BY Branch
ORDER BY avg_rating DESC;

-- Top 5 highest revenue categories

SELECT category, SUM(total) AS revenue
FROM walmart_table
GROUP BY category
ORDER BY revenue DESC
LIMIT 5;

-- How many transactions are above 1000?
SELECT COUNT(*) AS high_value_transactions
FROM walmart_table
WHERE total > 1000;

-- Revenue from High Value Transactions
SELECT SUM(total) AS high_value_revenue
FROM walmart_table
WHERE total > 1000;

-- Which City Generates Most Revenue?
SELECT City, SUM(total) AS revenue
FROM walmart_table
GROUP BY City
ORDER BY revenue DESC;

-- Best Performing Category by Average Rating

SELECT category, ROUND(AVG(rating),2) AS avg_rating
FROM walmart_table
GROUP BY category
ORDER BY avg_rating DESC;

-- Which category drives revenue and also maintains high customer satisfaction?

SELECT 
    category,
    SUM(total) AS revenue,
    ROUND(AVG(rating),2) AS avg_rating
FROM walmart_table
GROUP BY category
ORDER BY revenue DESC;

-- Categories with Revenue > 100,000
SELECT category, SUM(total) AS revenue
FROM walmart_table
GROUP BY category
HAVING SUM(total) > 100000
ORDER BY revenue DESC;


-- Most Profitable Categories

SELECT 
    category,
    SUM(total * profit_margin) AS total_profit
FROM walmart_table
GROUP BY category
ORDER BY total_profit DESC;


-- Profitability vs Revenue Comparison
SELECT 
    category,
    SUM(total) AS revenue,
    SUM(total * profit_margin) AS profit
FROM walmart_table
GROUP BY category
ORDER BY profit DESC;

-- Top 5 Most Profitable Cities

SELECT 
    City,
    SUM(total * profit_margin) AS total_profit
FROM walmart_table
GROUP BY City
ORDER BY total_profit DESC
LIMIT 5;

-- Contribution Percentage Analysis
-- What % of total company revenue each category contributes?
-- Find total revenue
SELECT SUM(total) AS overall_revenue
FROM walmart_table;

-- Contribution %
SELECT 
    category,
    SUM(total) AS revenue,
    ROUND(
        (SUM(total) / (SELECT SUM(total) FROM walmart_table)) * 100, 
        2
    ) AS revenue_percentage
FROM walmart_table
GROUP BY category
ORDER BY revenue_percentage DESC;

-- Ranking Categories by Revenue 
SELECT
    category,
    SUM(total) AS revenue,
    RANK() OVER (ORDER BY SUM(total) DESC) AS revenue_rank
FROM walmart_table
GROUP BY category;


-- Running Total of Revenue by Category

SELECT
    category,
    SUM(total) AS revenue,
    SUM(SUM(total)) OVER (ORDER BY SUM(total) DESC) AS running_total
FROM walmart_table
GROUP BY category;

-- Monthly Revenue Analysis
SELECT 
    MONTH(STR_TO_DATE(date, '%m/%d/%Y')) AS month,
    SUM(total) AS monthly_revenue
FROM walmart_table
GROUP BY month
ORDER BY monthly_revenue DESC;

-- Day of Week Analysis
SELECT 
    DAYNAME(STR_TO_DATE(date, '%m/%d/%Y')) AS day_name,
    SUM(total) AS revenue
FROM walmart_table
GROUP BY day_name
ORDER BY revenue DESC;

-- Time of Day Analysis
SELECT 
    HOUR(time) AS hour_of_day,
    SUM(total) AS revenue
FROM walmart_table
GROUP BY hour_of_day
ORDER BY revenue DESC;

-- Payment Method Revenue Contribution
SELECT 
    payment_method,
    SUM(total) AS revenue,
    ROUND(
        (SUM(total) / (SELECT SUM(total) FROM walmart_table)) * 100,
        2
    ) AS contribution_percentage
FROM walmart_table
GROUP BY payment_method
ORDER BY revenue DESC;

-- Average Rating by Category
SELECT 
    category,
    ROUND(AVG(rating),2) AS avg_rating
FROM walmart_table
GROUP BY category
ORDER BY avg_rating DESC;

-- Rating vs Revenue Correlation 
SELECT 
    category,
    ROUND(AVG(rating),2) AS avg_rating,
    SUM(total) AS revenue
FROM walmart_table
GROUP BY category
ORDER BY avg_rating DESC;

-- Top 10% Transactions (Using NTILE)
SELECT *
FROM (
    SELECT 
        invoice_id,
        total,
        NTILE(10) OVER (ORDER BY total DESC) AS percentile_group
    FROM walmart_table
) t
WHERE percentile_group = 1;

-- Average Basket Size
SELECT 
    ROUND(AVG(quantity),2) AS avg_items_per_transaction
FROM walmart_table;

-- Revenue by Branch

SELECT 
    Branch,
    SUM(total) AS revenue
FROM walmart_table
GROUP BY Branch
ORDER BY revenue DESC;

-- Profit Margin Analysis by Category
SELECT 
    category,
    ROUND(AVG(profit_margin),2) AS avg_margin
FROM walmart_table
GROUP BY category
ORDER BY avg_margin DESC;
